# Generated by Django 4.2.5 on 2023-09-09 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='published_date',
            field=models.DateField(default=datetime.date(2023, 9, 9)),
        ),
    ]
