# Generated by Django 4.2.5 on 2023-09-09 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaign_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
